apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  name: "{{ .Values.gitops.production.owner | default .Values.gitops.owner }}-{{ .Values.gitops.production.repo }}"
spec:
  provider: "{{ .Values.gitops.production.server | default .Values.gitops.server }}"
  providerName: '{{ .Values.gitops.gitKind | default "github" }}'
  org: "{{ .Values.gitops.production.owner | default .Values.gitops.owner }}"
  repo: "{{ .Values.gitops.production.repo }}"
  description: "the git repository for the Production environment"
  scheduler:
    kind: Scheduler
    name: ""
